# security.yaml

security:
    encoders:
        App\Entity\Utilisateurs:
            algorithm: auto # or specify the algorithm you're using (e.g., bcrypt)

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: "$2y$13$N53qo7Fn.YwZzYdILV1lzOEb8WtD5L1hi0te5EksL1IvXJiGsl2Ee" # Example hashed password
                        roles: 'ROLE_USER'

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login
